export const CREATE_USER = 'CREATE_USER';
export const DELETE_MESSAGE_LIST = 'DELETE_MESSAGE_LIST';
export const SWITCH_PAGE = 'SWITCH_PAGE';
export const WAIT_MESSAGE = 'WAIT_MESSAGE';
export const ENTER_MESSAGE = 'ENTER_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const CREATE_RESTART = 'CREATE_RESTART';
